M48
; DRILL file {KiCad 9.0.6} date 2026-02-22T19:02:12+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-22T19:02:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X68.89Y-85.77
X74.67Y-85.77
T2
X63.66Y-26.0
X63.66Y-89.013
X169.0Y-26.0
X169.0Y-89.013
M30
